import { useEffect, useState } from 'react'
import { Plus, Power } from 'lucide-react'
import { supabase } from '../services/supabase'
export default function Catalogos(){
 const [data,setData]=useState({tareas:[],establecimientos:[],lotes:[]});const [form,setForm]=useState({tarea:'',establecimiento:'',lote:'',farmId:''});const [msg,setMsg]=useState('')
 const load=async()=>{const [t,e,l]=await Promise.all([supabase.from('tareas').select('*').order('nombre'),supabase.from('establecimientos').select('*').order('nombre'),supabase.from('lotes').select('*').order('nombre')]);setData({tareas:t.data||[],establecimientos:e.data||[],lotes:l.data||[]});setForm(f=>({...f,farmId:f.farmId||String(e.data?.[0]?.id||'')}))};useEffect(()=>{load()},[])
 const add=async type=>{let result;if(type==='tarea')result=await supabase.from('tareas').insert({nombre:form.tarea.trim(),activo:true});if(type==='establecimiento')result=await supabase.from('establecimientos').insert({nombre:form.establecimiento.trim(),activo:true});if(type==='lote')result=await supabase.from('lotes').insert({nombre:form.lote.trim(),establecimiento_id:Number(form.farmId),activo:true});if(result.error)setMsg(result.error.code==='23505'?'El dato ya existe':result.error.message);else{setForm(f=>({...f,[type]:''}));setMsg('Guardado correctamente');load()}}
 const toggle=async(type,x)=>{await supabase.from(type).update({activo:!x.activo}).eq('id',x.id);load()}
 const Box=({title,type,rows})=><section className="card"><h2>{title}</h2><div className="row"><input value={form[type]} onChange={e=>setForm({...form,[type]:e.target.value})} placeholder={`Nueva ${title.toLowerCase()}`}/>{type==='lote'&&<select value={form.farmId} onChange={e=>setForm({...form,farmId:e.target.value})}>{data.establecimientos.map(x=><option key={x.id} value={x.id}>{x.nombre}</option>)}</select>}<button className="small" onClick={()=>add(type)}><Plus size={16}/>Agregar</button></div><div className="list">{rows.map(x=><article key={x.id}><b>{x.nombre}</b>{type==='lote'&&<span>{data.establecimientos.find(e=>e.id===x.establecimiento_id)?.nombre}</span>}<button className={x.activo?'small danger':'small'} onClick={()=>toggle(type==='tarea'?'tareas':type==='establecimiento'?'establecimientos':'lotes',x)}><Power size={16}/>{x.activo?'Desactivar':'Activar'}</button></article>)}</div></section>
 return <><header><p>AJUSTES</p><h1>Catálogos operativos</h1><span>Tareas, establecimientos y lotes</span></header>{msg&&<div className="global-message">{msg}</div>}<main className="grid three"><Box title="Tareas" type="tarea" rows={data.tareas}/><Box title="Establecimientos" type="establecimiento" rows={data.establecimientos}/><Box title="Lotes" type="lote" rows={data.lotes}/></main></>
}
