import { useEffect, useState } from 'react'
import { Camera, Pencil, Power } from 'lucide-react'
import { supabase } from '../services/supabase'
const dataUrlToBlob=async x=>await(await fetch(x)).blob()
export default function Empleados(){
 const [rows,setRows]=useState([]);const [form,setForm]=useState({id:null,legajo:'',nombre:'',photo:''});const [q,setQ]=useState('');const [msg,setMsg]=useState('');const [busy,setBusy]=useState(false)
 const load=async()=>{const {data,error}=await supabase.from('empleados').select('*').order('nombre');if(error)setMsg(error.message);else setRows(data||[])};useEffect(()=>{load()},[])
 const save=async()=>{const legajo=form.legajo.trim().toUpperCase(),nombre=form.nombre.trim();if(!legajo||!nombre)return setMsg('Complete legajo y nombre');setBusy(true);try{let photo_url=form.photo_url||null;if(form.photo?.startsWith('data:')){const blob=await dataUrlToBlob(form.photo);const path=`empleados/${legajo}-${Date.now()}.jpg`;const {error}=await supabase.storage.from('evidencias').upload(path,blob,{contentType:'image/jpeg'});if(error)throw error;photo_url=path}const payload={legajo,nombre,photo_url};const result=form.id?await supabase.from('empleados').update(payload).eq('id',form.id):await supabase.from('empleados').insert({...payload,activo:true});if(result.error)throw result.error;setForm({id:null,legajo:'',nombre:'',photo:''});setMsg(form.id?'Empleado actualizado':'Empleado guardado');await load()}catch(e){setMsg(e.code==='23505'?'El legajo ya existe':e.message)}finally{setBusy(false)}}
 const toggle=async x=>{const {error}=await supabase.from('empleados').update({activo:!x.activo}).eq('id',x.id);if(error)setMsg(error.message);else load()}
 const filtered=rows.filter(x=>(x.nombre+' '+x.legajo).toLowerCase().includes(q.toLowerCase()))
 return <><header><p>AJUSTES</p><h1>Empleados</h1><span>Alta, edición, foto y estado</span></header><main className="grid">
  <section className="card"><h2>{form.id?'Editar empleado':'Nuevo empleado'}</h2><label>Legajo<input value={form.legajo} onChange={e=>setForm({...form,legajo:e.target.value})}/></label><label>Nombre y apellido<input value={form.nombre} onChange={e=>setForm({...form,nombre:e.target.value})}/></label>
   <label className="camera"><Camera size={20}/>{form.photo?'Foto lista':'Cargar foto'}<input hidden type="file" accept="image/*" capture="user" onChange={e=>{const f=e.target.files?.[0];if(f){const r=new FileReader();r.onload=()=>setForm({...form,photo:r.result});r.readAsDataURL(f)}}}/></label>{form.photo&&<img className="preview" src={form.photo}/>}<button onClick={save} disabled={busy}>{busy?'Guardando...':'Guardar empleado'}</button>{form.id&&<button className="secondary" onClick={()=>setForm({id:null,legajo:'',nombre:'',photo:''})}>Cancelar edición</button>}{msg&&<div className="message">{msg}</div>}
  </section>
  <section className="card"><h2>Empleados registrados</h2><input placeholder="Buscar por nombre o legajo" value={q} onChange={e=>setQ(e.target.value)}/><div className="stats"><span>Total {rows.length}</span><span>Activos {rows.filter(x=>x.activo).length}</span><span>Inactivos {rows.filter(x=>!x.activo).length}</span></div><div className="list">{filtered.map(x=><article key={x.id}><b>{x.nombre}</b><span>Legajo: {x.legajo}</span><span>{x.activo?'Activo':'Inactivo'}</span><div className="row"><button className="small" onClick={()=>setForm({id:x.id,legajo:x.legajo,nombre:x.nombre,photo:'',photo_url:x.photo_url})}><Pencil size={16}/>Editar</button><button className={x.activo?'small danger':'small'} onClick={()=>toggle(x)}><Power size={16}/>{x.activo?'Desactivar':'Activar'}</button></div></article>)}</div></section>
 </main></>
}
